blank_issues_enabled: false
contact_links:
  - name: Request a new feature
    url: https://www.google.com
    about: Request new features and vote on the ones that are important to you
  - name: Get support or ask a question
    url: https://www.google.com
    about: Use the support system to get help and ask questions
