name: "General issue"
description: "This is a test issue"
title: "[Bug]: "
labels: []
body:
 - type: markdown
   attributes:
     value: |
       Thanks for taking the time to fill out this bug report!

       ## **Before Submitting:**

       * Please search to make sure this issue has not been opened already.
       * If this is a question about how to integrate MetaMask with your project, please ask in our [Community forum](https://community.metamask.io/c/developer-questions/) instead. This will get your question answered more quickly and make it easier for other devs to find the answer in the future.
 - type: textarea
   id: what-happened
   attributes:
     label: Describe the bug
     description: What happened? What did you expect to happen? Please include screenshots if applicable!
     placeholder: A clear and concise description of what the bug is
   validations:
     required: true