name: "General issue 2"
about: "For any issues"
title: ""
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## **Description**

  - type: textarea
    id: description
    attributes:
      label: What is this about?
      placeholder: Describe the issue here.

