name: Add release label to PR and linked issues when PR gets merged

on:
  pull_request:
    types:
      - closed

jobs:
  add_release_label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
          
      - name: Add release label to PR and linked issues
        id: add_releease_label_to_pr_and_linked_issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_REPO: ${{ github.repository }}
          NEXT_RELEASE_CUT_NUMBER: ${{ env.NEXT_RELEASE_CUT_NUMBER }}
        run: node .github/scripts/add_releease_label_to_pr_and_linked_issues.js
