name: Label PR and Linked Issues with Next Release Cut Number

on:
  pull_request:
    types:
      - closed

jobs:
  add_release_label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Get issues to label (PR and linked issues)
        id: get_issues_to_label
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO="${{ github.repository }}"
          
          echo "Fetching PR #$PR_NUMBER in $REPO"
          PR_ISSUE=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq '{number: .number, owner: .base.repo.owner.login, repo: .base.repo.name}')
          
          echo "PR_ISSUE: #$PR_ISSUE"
          LINKED_ISSUES_TEST=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq '{linkedIssues: .linkedIssues}')
          echo "LINKED_ISSUES_TEST: #$LINKED_ISSUES_TEST"
          
          echo "Fetching linked issues for PR #$PR_NUMBER in $REPO and other repos"
          LINKED_ISSUES=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq ".linkedIssues.nodes[]? | {number: .number, owner: .repository.owner.login, repo: .repository.name}") || "[]"
          
          ALL_ISSUES_TO_LABEL="[$PR_ISSUE,${LINKED_ISSUES}]"
          echo "::set-output name=all_issues_to_label::${ALL_ISSUES_TO_LABEL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add release label to PR and linked issues
        uses: actions/github-script@v5
        with:
          script: |
            const all_issues_to_label_json = ${{ steps.get_issues_to_label.outputs.all_issues_to_label }};
            const all_issues_to_label = all_issues_to_label_json ? JSON.parse(all_issues_to_label_json) : [];
            const next_release_cut_number = process.env.NEXT_RELEASE_CUT_NUMBER; // This value is defined in section "Secrets and variables">"Actions">"Variables">"New repository variable" in the settings of this repo. It needs to be updated every time a new release is cut. Example value: 6.5

            if (!next_release_cut_number) {
              throw new Error("The NEXT_RELEASE_CUT_NUMBER environment variable is not defined.");
            }

            const addLabel = async (issue_number, owner, repo) => {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: issue_number,
                labels: [`release-${next_release_cut_number}`],
              });
            };

            // Add label to PR and linked issues
            for (const issue of all_issues_to_label) {
              await addLabel(issue.number, issue.owner, issue.repo);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
