name: Add release label to PR and linked issues when PR gets merged

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  add_release_label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get workflow ID
        id: get-workflow-id
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo
            })
            const workflow = workflows.data.workflows.find(w => w.name === 'set env variable') // Name of the workflow where the artifcat containing "NEXT_RELEASE_CUT_NUMBER" is created
            return workflow.id
        
      - name: Get the latest successful workflow run ID
        id: get-workflow-run-id
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: ${{ steps.get-workflow-id.outputs.result }},
              event: 'workflow_dispatch',
              status: 'success'
            })
            return workflows.data.workflow_runs[0].id
        
      - name: Download environment variable from artifact # the artifact is created by the github action used to create the release branch when a new release is cut
        uses: actions/download-artifact@v2
        with:
          name: env_var
          run_id: ${{ steps.get-workflow-run-id.outputs.result }}
        continue-on-error: true  # So the workflow doesn't fail if the artifact does not exist
        
      - name: Load environment variable
        id: load_var
        run: |
          echo "Checking for environment variable and artifact..."

          if [ -n "${{ vars.NEXT_RELEASE_CUT_NUMBER }}" ]; then
            echo "Environment variable NEXT_RELEASE_CUT_NUMBER is set:"
            echo "${{ vars.NEXT_RELEASE_CUT_NUMBER }}"
            echo "::set-output name=NEXT_RELEASE_CUT_NUMBER::${{ vars.NEXT_RELEASE_CUT_NUMBER }}"
          elif [ -f env_var.txt ]; then
            echo "Artifact env_var.txt exists with contents:"
            cat env_var.txt
            echo "::set-output name=NEXT_RELEASE_CUT_NUMBER::$(cat env_var.txt)"
          else
            echo "Neither environment variable nor artifact found."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn
    
      - name: Install dependencies
        run: yarn
          
      - name: Add release label to PR and linked issues
        id: add_release_label_to_pr_and_linked_issues
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NEXT_RELEASE_CUT_NUMBER: ${{ steps.load_var.outputs.NEXT_RELEASE_CUT_NUMBER }}
        run: npm run add_release_label_to_pr_and_linked_issues
