name: Require Changeset

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check for changeset
        run: |
          if ! npx changeset status --since=origin/main; then
            echo "❌ Please run \`yarn changeset\` locally, to add a user-facing changelog entry on your PR (or 'null' if not user-facing)."
            exit 1
          fi
