name: Set next release cut number
on:
  workflow_dispatch:
    inputs:
      next-release-cut-number:
        description: 'Input next release cut number'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Save next release cut number in a text file
      run: echo "${{ github.event.inputs.next-release-cut-number }}" > next_release_cut_number.txt

    - name: Upload text file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: next_release_cut_number
        path: next_release_cut_number.txt
