name: set env variable
on:
  workflow_dispatch:
    inputs:
      next-release-cut-number:
        description: 'Input next release cut number'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variable
      run: echo "NEXT_RELEASE_CUT_NUMBER=${{ github.event.inputs.next-release-cut-number }}" > env_var.txt

    - name: Load and test environment variable
      run: |
        source env_var.txt
        echo $NEXT_RELEASE_CUT_NUMBER

    - name: Upload environment variable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: env_var
        path: env_var.txt
