name: Zenhub Label Sync

on:
  workflow_dispatch:
  repository_dispatch:
    types: [zenhub.issue_transferred]

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Update labels
      uses: actions/github-script@v5
      with:
        script: |
          const columnMapping = {
            "Product Backlog": "product-backlog",
            "Sprint Backlog": "sprint-backlog",
            "In Progress": "in-progress",
            "Review/QA": "review-or-qa",
            "Done": "done"
          };
          const context = github.context;
          const columnName = context.payload.client_payload.webhook.metadata.column_name;
          const labelName = columnMapping[columnName];

          if (!labelName) {
            console.log(`Column "${columnName}" not found in columnMapping. Skipping label update.`);
            return;
          }

          const issue = context.payload.client_payload.webhook.issue;
          const repo = context.payload.client_payload.webhook.repository;

          const currentLabels = issue.labels.map(label => label.name);
          const newLabels = currentLabels
            .filter(name => !Object.values(columnMapping).includes(name))
            .concat([labelName]);

          await github.rest.issues.setLabels({
            owner: repo.owner.login,
            repo: repo.name,
            issue_number: issue.number,
            labels: newLabels
          });
