name: Zenhub Label Sync

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Event type'
        required: true
      github_url:
        description: 'GitHub URL'
        required: true
      organization:
        description: 'Organization name'
        required: true
      repo:
        description: 'Repository name'
        required: true
      user_name:
        description: 'User name'
        required: true
      issue_number:
        description: 'Issue number'
        required: true
      issue_title:
        description: 'Issue title'
        required: true
      to_pipeline_name:
        description: 'To pipeline name'
        required: true
      workspace_id:
        description: 'Workspace ID'
        required: true
      workspace_name:
        description: 'Workspace name'
        required: true
      from_pipeline_name:
        description: 'From pipeline name'
        required: true

  repository_dispatch:
    types: [zenhub.issue_transferred]
    
jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Update labels
      uses: actions/github-script@v5
      with:
        script: |
          console.log("AAAAAAAAA");
          console.log(JSON.stringify(github));
          const columnMapping = {
            "Product Backlog": "product-backlog",
            "Sprint Backlog": "sprint-backlog",
            "In Progress": "in-progress",
            "Review/QA": "review-or-qa",
            "Done": "done"
          };
          const columnName = github.context.payload.client_payload.webhook.metadata.column_name;
          const labelName = columnMapping[columnName];

          if (!labelName) {
            console.log(`Column "${columnName}" not found in columnMapping. Skipping label update.`);
            return;
          }

          const issue = github.context.payload.client_payload.webhook.issue;
          const repo = github.context.payload.client_payload.webhook.repository;

          const currentLabels = issue.labels.map(label => label.name);
          const newLabels = currentLabels
            .filter(name => !Object.values(columnMapping).includes(name))
            .concat([labelName]);

          await github.rest.issues.setLabels({
            owner: repo.owner.login,
            repo: repo.name,
            issue_number: issue.number,
            labels: newLabels
          });
